enum MOIM_REQUEST_TYPE {
  ALL = 'ALL',
  SELF = 'SELF',
  MUSIC = 'MUSIC',
  ANIMAL = 'ANIMAL',
  PHOTO = 'PHOTO',
  RELIGION = 'RELIGION',
  VOLUNTEER = 'VOLUNTEER',
  ARTICLE = 'ARTICLE',
  LANGUAGE = 'LANGUAGE',
  HUMANITY = 'HUMANITY',
  TECH = 'TECH',
  SPORTS = 'SPORTS',
}

enum MOIM_JOIN_STATUS {
  COMPLETE = 'COMPLETE',
  LOADING = 'LOADING',
  REJECT = 'REJECT',
  DELETED = 'DELETED',
}

export {MOIM_REQUEST_TYPE, MOIM_JOIN_STATUS};
