enum MOIM_REQUEST_TYPE {
  ALL = 'ALL',
  SELF = 'SELF',
  MUSIC = 'MUSIC',
  ANIMAL = 'ANIMAL',
  PHOTO = 'PHOTO',
  RELIGION = 'RELIGION',
  VOLUNTEER = 'VOLUNTEER',
  ARTICLE = 'ARTICLE',
  LANGUAGE = 'LANGUAGE',
  HUMANITY = 'HUMANITY',
  TECH = 'TECH',
  SPORTS = 'SPORTS',
}

export {MOIM_REQUEST_TYPE};
