enum MOIM_REQUEST_TYPE {
  ALL = 'ALL',
  SELF = 'SELF',
  MUSIC = 'MUSIC',
  ANIMAL = 'ANIMAL',
  PHOTO = 'PHOTO',
  RELIGION = 'RELIGION',
  VOLUNTEER = 'VOLUNTEER',
  ARTICLE = 'ARTICLE',
  LANGUAGE = 'LANGUAGE',
  HUMANITY = 'HUMANITY',
  TECH = 'TECH',
  SPORTS = 'SPORTS',
  ETC = 'ETC',
}

enum MOIM_JOIN_STATUS {
  COMPLETE = 'COMPLETE',
  LOADING = 'LOADING',
  REJECT = 'REJECT',
  DELETED = 'DELETED',
}

enum USER_PROVIDER {
  LOCAL = 'LOCAL',
  NAVER = 'NAVER',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  KAKAO = 'KAKAO',
  UNREGISTERED = 'UNREGISTERED',
}

enum COMMENT_STATUS {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
}

enum MOIM_ROLE {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  ALL = 'ALL',
}

export {
  MOIM_REQUEST_TYPE,
  MOIM_JOIN_STATUS,
  USER_PROVIDER,
  COMMENT_STATUS,
  MOIM_ROLE,
};
